name: "ClassesFightArena"
main: "me.hapyl.fight.Main"
version: 1.5-SNAPSHOT
api-version: "1.17"
description: ${description}
depend: [ "EternaAPI" ]
authors: [ "hapyl", "sdimas74", "DirtyEl", "DiDenPro" ]